Allow hotfix branch pattern (#5)
* Allow hotfix branch pattern

* fix description

* Test branch exiustance and output shugar

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -31,6 +31,19 @@ inputs:
 
     required: false
 
+  hotfix-branch-prefix:
+    description: |
+      Branch prefix allowed for hotfix. Tags on this branch will set is_hotfix to true.
+
+      Make sure the branch is available with git fetch (if fetch-depth is unset or > 0)
+
+      ```yaml
+      - name: Fetch hotfix branch (for action-metadata commit check)
+        run: |
+        git fetch --no-tags --prune --depth=1000 origin '+refs/heads/stable/*:refs/remotes/origin/stable/*'
+      ```
+    required: false
+
 outputs:
   publishable:
     description: |
@@ -68,9 +81,11 @@ runs:
       run: |
         PUBLISHABLE=false
         IS_RELEASE=false
+        IS_HOTFIX=false
         VERSION=0.0.0-SNAPSHOT
         DEFAULT_BRANCH=${{ github.event.repository.default_branch }}
         RELEASE_BRANCH=${{ inputs.release-branch }}
+        HOTFIX_BRANCH_PREFIX=${{ inputs.hotfix-branch-prefix }}
 
         LATEST_VERSION=${{ steps.latest.outputs.tag }}
         LATEST_VERSION=${LATEST_VERSION#v}
@@ -88,6 +103,20 @@ runs:
         if [[ $GITHUB_REF =~ refs/tags/v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
           VERSION=${GITHUB_REF#refs/tags/v}
           PUBLISHABLE=$(git merge-base --is-ancestor "$GITHUB_SHA" "origin/$RELEASE_BRANCH" && echo "true" || echo "false")
+
+          if [[ "$PUBLISHABLE" == "false" && ! -z "$HOTFIX_BRANCH_PREFIX" ]]; then
+            # Maybe we have an hotfix. Must be ancestor to the corresponding stable hotfix branch
+            HOTFIX_BRANCH="${HOTFIX_BRANCH_PREFIX%/}/v${VERSION%.*}.x"
+            if [[ ! -z "$(git ls-remote --heads origin ${HOTFIX_BRANCH})" ]]; then
+              PUBLISHABLE=$(git merge-base --is-ancestor "$GITHUB_SHA" "origin/$HOTFIX_BRANCH" && echo "true" || echo "false")
+              if [[ "PUBLISHABLE" == "true" ]]; then
+                IS_HOTFIX="true"
+              fi
+            else
+              echo "Hotfix branch '${HOTFIX_BRANCH}' does not exists. Could not publish tag '${VERSION}'"
+            fi
+          fi
+
           IS_RELEASE="$PUBLISHABLE"
         elif [[ $GITHUB_REF == refs/tags/* ]]; then
           VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed -r 's#/+#-#g')
@@ -103,6 +132,15 @@ runs:
           VERSION=pr-${{ github.event.number }}
         fi
 
-        echo ::set-output name=is-release::$IS_RELEASE
-        echo ::set-output name=publishable::$PUBLISHABLE
-        echo ::set-output name=version::$VERSION
+        echo "is-release=$IS_RELEASE" >> $GITHUB_OUTPUT
+        echo "publishable=$PUBLISHABLE" >> $GITHUB_OUTPUT
+        echo "version=$VERSION" >> $GITHUB_OUTPUT
+        echo "is-hotfix=$IS_HOTFIX" >> $GITHUB_OUTPUT
+
+        echo "### Aplication metadata" >> $GITHUB_STEP_SUMMARY
+        echo "|Output|Value|" >> $GITHUB_STEP_SUMMARY
+        echo "|:---|:---|" >> $GITHUB_STEP_SUMMARY
+        echo "|__is-release__|$IS_RELEASE|" >> $GITHUB_STEP_SUMMARY
+        echo "|__publishable__|$PUBLISHABLE|" >> $GITHUB_STEP_SUMMARY
+        echo "|__version__|$VERSION|" >> $GITHUB_STEP_SUMMARY
+        echo "|__is-hotfix__|$IS_HOTFIX|" >> $GITHUB_STEP_SUMMARY
